### ISSUE TITLE
test what happens if estimateParams=0 and fix_P and/or fix_b =0

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#118]
Have we tested to see what happens if in the optimization_diagnostics sheet we have the following:

* estimateParams=0, fix_P=0, fix_b =0
* estimateParams=0, fix_P=1, fix_b =0
* estimateParams=0, fix_P=0, fix_b =1

In each of these cases, the value of "estimateParams" should govern and neither P nor b should be estimated, but we should check to see if this is the case.

**Comment by tessaam** [comment]
There was a MATLAB error when setting estimateParams=0 for P=0 and b=0. There was a .xlsx output, gene plots, and an optimization_diagnostics plot, but no .mat file. 
 Reference to non-existent field 'reg_out'.
 Error in output (line 140)
 outputDiag{3,2} = GRNstruct.GRNOutput.reg_out;
 Error in GRNmodel (line 34)
 GRNstruct = output(GRNstruct);

I ran P=0 and b=0 with estimateParams=1 and there was no error. MATLAB output  a .xlsx output, gene plots, optimization_diagnostics plot, and .mat output. 
I also ran P=0 and b=0 with estimateParams=1 and there was no error. MATLAB output a .xlsx output and .mat output. There was no optimization_diagnostics plot output.

**Comment by trixr4kdz** [comment]
@bengfitzpatrick The assignment for variable GRNstruct.GRNOutput.reg_out (as well as for GRNstruct.GRNOutput.counter) should be outside of the if statement for if estimateParams is true in the lse.m routine since we would want the penalty_out and counter to be outputted no matter what. I tried running that and it does not throw the error, but the optimization_diagnostics image is a blank page.

**Comment by bengfitzpatrick** [comment]
fixed this. ready for testing once I get the code uploaded.

**Comment by bengfitzpatrick** [comment]
merge L-curve and beta is new issue
