### ISSUE TITLE
McNair Symposium/SACNAS 2015 Conference

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#122]
The McNair Symposium is actually going to be held on October 3rd instead of what @trixr4kdz originally thought as the week before the SACNAS Conference. The SACNAS Conference will be held on Oct 29-31 in Washington, DC. @trixr4kdz will be doing a poster presentation about the GRNmap research over the summer. She will need to make a poster and upload it to the "Documents" folder.

**Comment by trixr4kdz** [comment]
I've uploaded a draft of my research poster titled Roque - McNair/SACNAS 2015 Poster in the documents folder in master. I've taken some information from the LMU symposium that @juansc and I made.

**Comment by kdahlquist** [comment]
@trixr4kdz , I've had a chance to review your poster.  Here is my feedback:

* remove the abstract
* move the activity diagram to either the middle or bottom of the poster
* you need to introduce GRNmap and what it does more graphically.  You should include the equations, a network diagram, and the flow chart that you used to put it in context from your final McNair presentation for the summer.
* The flow chart that Trixie made that shows all 16 ways to run the program would also be helpful
* Just like in an oral presentation, each section heading of your poster should be a longer phrase or sentence that gives that *message* of that section, not just the topic.
* We may not have room for the list of worksheets, but if we do, we have better documentation of what the sheets contain on our wiki, please use the information from there.
* You should include as bullet points what you accomplished in the summer, like the slide you had for the McNair summer presentation.
* in terms of Future work, we should be a little more specific as to the tasks we are actually working on now.  Some of the things you list are in the too-far-away future.  Our shorter term goals are:
    * complete the testing framework for all current functionality of the code, fixing bugs and refactoring code as needed
    * clean up the variable names, and how the program discovers which strains are present and which genes are deleted
    * move the documentation for how to use GRNmap from the wiki to the documentation page of the web site
    * add functionality so that GRNmap computes the within- and between-strain ANOVA values
* you talk about making a Mac version, but that is not one of our priorities right now, we may never get to that (we don't even have it as an issue yet)
* you talk about adding radio buttons and check boxes in Excel, and again that is a very low priority right now (we don't have an issue for that either).
* For the sigmoidal model at least, you can reference a paper that is in press:

Dahlquist, K.D., Fitzpatrick, B.G., Camacho, E.T., Entzminger, S.D., and Wanner, N.C. (2015) Parameter Estimation for Gene Regulatory Networks from Microarray Data: Cold Shock Response in Saccharomyces cerevisiae. Bulletin of Mathematical Biology, in press.

We will talk more at the meeting today.  Since you are presenting a week from Saturday, we want to print it out by a week from Thursday, so we will need to iterate some new versions before then.

**Comment by trixr4kdz** [comment]
We will need to shoot for Monday for a new version of the poster so we can print it by Thursday.

**Comment by trixr4kdz** [comment]
I've uploaded the newest revision of the poster in both .pdf and .pptx format

**Comment by kdahlquist** [comment]
I just downloaded your latest version and will try to get some comments back to you by tomorrow.

I just realized that you were uploading these files to the master branch.  In terms of process, we should never be committing new changes to the master branch--it should always remain pristine--all new work, even posters and documentation that don't really affect the code, should be pushed to a branch instead.

So, in the interim before we do some merges, will you take these down from master and post them to the beta branch?  Thanks.

**Comment by trixr4kdz** [comment]
Ok, I just moved them.

**Comment by kdahlquist** [comment]
I'm going to write up the feedback to your poster here.  So that I don't lose my changes, I am going to save the comment quite frequently and then go back and edit the same comment so that all of the changes are in the same comment.  I don't think that it will generate a new e-mail every time I edit the comment, so you will need to view it on GitHub in order to see it all.

* I like the overall layout and organization better now.  However, there are still a few tweaks that need to be made to the layout.
* Reference should be on the far right, Acknowledgments in the middle, and Future Work on the left.
* I think your fonts are too large for the headings and body text and your title is too small.  The overall poster title should be the largest font on the page.  The section headers should be about 36 point font and the body text should be about 24 point font.  You will need to increase your title font.  Also, don't leave one word of your title hanging by itself on the second line.  There is a natural break at the comma in your title to break to the second line.  Your title area will get bigger with these changes, but your other sections will get smaller, so it should compensate.

**Comment by trixr4kdz** [comment]
I've updated the poster in the beta branch

**Comment by kdahlquist** [comment]
I can look at it later tonight.


Kam D. Dahlquist, Ph.D.
Associate Professor of Biology
Loyola Marymount University
http://myweb.lmu.edu/kdahlqui



-------- Original message --------

**Comment by kdahlquist** [comment]
Its looking good.  I have a couple minor comments after which it will be ready to print:
* The title for the top left section should read: "GRNmap uses ODEs to Model Gene Regulatory Networks"
* The title for the top middle section should read: "GRNmap Uses Data Provided by Our Interdisciplinary Research Group"
* You should go through one more time and make sure that all sentences have periods and everything is spell- and grammar-checked.  Getting someone else from the group to proofread it would be good, if that's possible.  Unfortunately, I won't have time myself because I've got a crazy day tomorrow.

**Comment by trixr4kdz** [comment]
McNair Symposium went well! Question I have for later though, since I already have a printed poster, should I just use that for the SACNAS conference at the end of the month, or would you like to look at it some more and see it there is anything you would like to change?

**Comment by kdahlquist** [comment]
Let's see how things go.  If I have time to look at it again and give you feedback in enough time before you leave, maybe we'll change some things.  However, the way things are looking, I may not get to it, so we'll just go with the one you have.  Remind me again at out meeting next week and I'll be able to give you a firmer answer.

**Comment by kdahlquist** [comment]
@trixr4kdz is back from the conference!
