### ISSUE TITLE
Edge case where optimization diagnostic is not created

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#123]
If GRNmap takes less than 100 iterations, the optimization_diagnostic figure is never generated. However, the first figure is called 'optimization_diagnostic' by default. So if GRNmap finishes in less than 100 iterations, the first figure that is generated, one of the strains, is called 'optimization diagnostics'. We should change it so that we only label the first figure as 'optimization_diagnostics' if the total number of iterations is greater than or equal to 100.

**Comment by trixr4kdz** [comment]
I've fixed the code so that the 'optimization_diagnostics' is only created when the number of iterations is less than 100.

**Comment by kdahlquist** [comment]
I need more information on this one, the previous comment by @trixr4kdz does not make sense to me:

"I've fixed the code so that the 'optimization_diagnostics' is only created when the number of iterations is less than 100."

Do you mean that when the number of iterations is *more* than 100?

It seems to me that we might want this figure to be made even if the number of iterations is less than 100, is that what you meant?

Also, @juansc, which file generates this problem so I can run it myself.

**Comment by trixr4kdz** [comment]
Oh sorry, my bad. It's supposed to say "I've fixed the code so that the 'optimization_diagnostics' is only created when the number of iterations is MORE than 100". 

In other words, we thought that since the very first figure saved, which right now is always the "optimization_diagnostics.jpg", isn't created when the number of iterations is less than 100, that we are not going to save "Figure 1" for counter < 100 since it just creates a duplicate image for the first deletion strain.

**Comment by kdahlquist** [comment]
We won't output the figure when the  number of iterations is less than 100.  @kdahlquist will verify the filename bug is fixed.  We need to make sure to document for the user not to expect the graph if there is less than 100 iterations.

**Comment by kdahlquist** [comment]
Verified fixed on the beta branch with the file mentioned above (from the beta branch).  Am closing.
