### ISSUE TITLE
New naming convention has been implemented but the test files still have the old names

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#129]
The new naming convention from the 09/16/15 meeting has been implemented. The test spreadsheets should then be updated to reflect the changes.

**Comment by kdahlquist** [comment]
Actually, I thought we were utilizing test-driven development now.  @dondi can correct me if I'm wrong, but the proper procedure would be to write the test, fail the test, fix the code to pass the test, write another test, etc., instead of just fixing the code and writing the test afterward.  Thus, I think it is the job of our developers to create the test input workbooks, write the tests, and then commit the workbooks and tests.  I'm reassigning this to @trixr4kdz because it looks like she is the one working on this, but @juansc could assist.

**Comment by dondi** [comment]
Yes, for future reference, to keep with the discipline of TDD, the order of activities should have been, *on a test by test basis*: (a) change the test code to reflect the new names first, (b) run the tests to see that they fail, then (c) rename the files so that the tests pass again. Just like physical routines we we have to consciously go through the moves initially (e.g., a tennis stroke, a golf swing, martial arts), it is important to set our minds to the process so that it becomes more and more natural, to the point where we cannot think of a better way to do things.

**Comment by trixr4kdz** [comment]
Ok, in that case, I think it might be best if I checkout the commit before I made any changes since it would seem that @bengfitzpatrick and @juansc are working in beta and are receiving errors from the changed names. I will continue with adapting the naming convention in test_suite branch and will merge when done.

**Comment by trixr4kdz** [comment]
We have recently merged test_suite and beta and all the tests (we have 25 so far) are now passing, except for one about a fix mentioned in issue #145. I am now deleting test_suite since it is now even with beta.

**Comment by kdahlquist** [comment]
All test files will need to be changed to the new convention.

**Comment by trixr4kdz** [comment]
All the tests in the test_files folder have been changed for the new naming convention. However, I think that some of them have outdated sheets (e.g. some files don't have the production rates, sigmas, etc. worksheets when they are supposed to since these were created before the bug fixes were done).

**Comment by kdahlquist** [comment]
This is the next priority after cleaning up #52 and #119 .  We need to get all of the test spreadsheets up to the new standard for the naming convention.  This goes along with the bug fix for #155 where there was a problem with the number formatting of the timepoints on the expression worksheets.

**Comment by kdahlquist** [comment]
While you are working on this, would you please make sure that all of the files in the "test_files" directory are in the .xlsx format?  (.xls files will need to be opened in Excel, and "Saved As" .xlsx.

Our open dialog restricts the user to viewing .xlsx files and we should move over to this standard in our test_files.

**Comment by kdahlquist** [comment]
Closing this because it is complete.
