### ISSUE TITLE
Fix Existing Test Suite

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#139]
Recent changes in the code did not follow TDD. The output files need to be updated to fit the latest changes. We have to take care of the following list of tests:

* readInputSheetTest/testReadInputs
* readInputSheetTets/testSimTime
* outputTest/testOutputSheetsExist
* outputTest/testSigmaValues
* outputTest/testSimTime
* outputTest/testLSE
* outputTest/testGraphs

Note: This issue might be divided to be shared by @juansc and @trixr4kdz.

**Comment by trixr4kdz** [comment]
test_suite has been fixed so the above tests now pass except for testGraphs. testGraphs will pass if make_graphs = 1, but fails when make_graphs = 0. I created this part of the test with the thought that I should run the "graphs" routine instead of the "output.m" routine since the "output.m" routine would just override the outputs that have the same name in the that folder. For now, I would suggest modifying the output sheets in the sixteen_files folder so that they are named differently from what GRNmap creates (something like "4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_graph_output_archived" like what @bengfitzpatrick  did before to prevent overwriting the existing output files). It isn't possible currently to write output into temporary files since that would mean modifying the "output.m" routine itself to allow for saving into temp files.

After fixing testGraphs

**Comment by trixr4kdz** [comment]
I'm retracting my previous comment to modify the output sheet names since I have made it so the outputs generated during the tests are placed in the temporary folder. Will continue to work on this at a later time.

**Comment by juansc** [comment]
We have changed the tests so they are up to date. We should close this issue since other, more specific aspects of testing can have their own issue.

**Comment by kdahlquist** [comment]
We'll review this and close it at the meeting--I just want to make sure that any further tasks are indeed broken out into their own issues.
