### ISSUE TITLE
Expression timepoints are not read correctly from excel

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#154]
@juansc and I recently tried to manually perform the calculations for figuring out the LSE. When we performed the calculations for the file "perturbation_tests/math_post_L-curve/4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixp-1_no-graph_test1", our expected LSE = 
0.0126680575719571 but the reported LSE = 0.0101163680400687. We tried to trace back the cause of the problem and discovered that the expression timpoints are not being read correctly.

In the file, the expression timepoints (not the optimized expression timepoints) should be the following:
[0.4    0.4    0.4    0.8    0.8    0.8    1.2    1.2    1.2    1.6    1.6    1.6]

GRNmap seems to be seeing these numbers as they are written here, but does not recognize that the three instances of timepoint 1.2 are all the same. For example, if we try to see if 1.2 equals 1.2, MATLAB would tell us that they are not equal to each other. 

We have yet to determine the cause of this phenomenon.

**Comment by kdahlquist** [comment]
Is it because of a datatype mismatch?  Is one of the 1.2's being interpreted as a text string instead of a number (or something like that)?

**Comment by juansc** [comment]
We're not sure. On the Excel sheet all numbers have the same format. But the first two instances of 1.2 are being interpreted differently than the last one.

**Comment by bengfitzpatrick** [comment]
Dr. Dahlquist is likely to be on the right track.  In excel, click on each cell of the time list, and look at what excel thinks the format of the cell is.

**Comment by trixr4kdz** [comment]
We thought of that, but it seems that all of the numbers are in the same "General" format.

**Comment by bengfitzpatrick** [comment]
They should be in number format, not general format.

**Comment by trixr4kdz** [comment]
This problem does not happen with the rest of the timepoints even though they are also in general format. It only happens with the first two 1.2 timepoints. The rest of the data that exist in the sheets are also in general format, but they seem to be read just fine.

**Comment by kdahlquist** [comment]
Even though they are all in general format, there just could be some weird stuff going on.  There could be some "ghost" formatting leftover from some copy/paste operation or something.  Try changing all of them to explicitly number format and see what happens.

**Comment by bengfitzpatrick** [comment]
I agree with Dr. Dahlquist.  Please try it.

**Comment by trixr4kdz** [comment]
I changed the format to number instead of general, but still ran into the same problem. Since that didn't work, I decided to just copy/paste the 1.2 value that works into the cells that don't and that fixed it. However, for future work, I think that we would still need to fix the code so that the same timepoints on excel are indeed equal.

**Comment by kdahlquist** [comment]
I think that this does actually confirm our suspicion that it was a datatype mismatch; it's just that changing the type in Excel did not fix the problem (which I've seen before in other contexts).

What we will need to do is confirm that all of the timepoints are numbers when they are read in originally.  You should talk to @anuvarsh about this because she has been doing a bunch of tests for GRNsight about reading in the input sheets and making sure that they are formatted correctly.  It's possible that we could use or adapt some of her test spreadsheets for our use.

**Comment by kdahlquist** [comment]
Also, please commit the corrected test input sheet.  We should save the "bad" one for a future test, but we should make sure that this problem isn't happening with other input sheets that we think are working properly.

**Comment by trixr4kdz** [comment]
Reformatting the timepoints seem to have corrected the LSE calculation. 

However, we spotted another discrepancy in the SSE calculations.
![evidence](https://cloud.githubusercontent.com/assets/8975300/11256301/0385a2dc-8e00-11e5-9951-f0b317e9e481.PNG)
It would seem that the dcin5 SSE is the cumulative sum of both wt and dcin5 SSEs

**Comment by bengfitzpatrick** [comment]
I will have a look at that, Trixie.  What's the best branch for me to download?

**Comment by trixr4kdz** [comment]
I would say the beta branch would be the one to download since I've only been using that branch.

**Comment by dondi** [comment]
I looked at this with @juansc and @trixr4kdz and I showed them how to unpack the .xlsx file so that you can see the .xml documents that comprise the spreadsheet. We located the .xml file that holds the sheet in question, and indeed, *right at the level of the .xml file*, those cells were actually stored as `1.20000000000000002`, `1.20000000000000002`, and `1.2`, respectively.

i.e., The file itself is showing that very data, and MATLAB is actually reading it accurately, but it is *Excel* that is somehow truncating it via some unknown logic so that an Excel user sees `1.2` exclusively.

My suggestion is to go ahead and just edit the file. This imprecision may be an artifact of an old bug that has since gone away, or it might be a conversion artifact from .xls to .xlsx format. Either way, if it is fixed, it may be sufficient to leave it at that. I suggested that people email the fixed file around, open and edit it, then reopen it to see if that extra digit shows up again. If it does…we can talk about that. If it doesn’t, then maybe we can just fix it and forget it.

**Comment by kdahlquist** [comment]
I am going to close this one because it is now redundant with #155 .

**Comment by juansc** [comment]
The name of the problem file has been changed to '4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-1_fixP-1_no-graph_test1_LCurve'.
