### ISSUE TITLE
readInputSheet error when running master GRNmap code on new input sheets

### ISSUE THREAD

**Issue by GraceJohnson** [kdahlquist/GRNmap#156]
@Nwilli31 and I just attempted to run four separate input sheets from our newly made network families.  This is the error that appeared: 

GRNmodel
Cell contents reference from a non-cell array object.

Error in readInputSheet (line 67)
    currentStrain = Strain{index};

Error in GRNmodel (line 30)
GRNstruct = readInputSheet(GRNstruct);

I'll provide the file I used as an input sheet here:

[dHAP4_34_gene_network_deletion_added_input_GJ.xlsx](https://github.com/kdahlquist/GRNmap/files/49278/dHAP4_34_gene_network_deletion_added_input_GJ.xlsx)

We tried briefly to identify the source of the error. We thought the blanks in the log2 expression sheets may have been the problem, but when running an older file without these blanks (and formatting the file appropriately) we got the same errors.

**Comment by Nwilli31** [comment]
@GraceJohnson and I were using the master branch instead of using the beta branch

**Comment by kdahlquist** [comment]
@GraceJohnson and @Nwilli31: could you try running the latest release version of the code from the downloads web site (version 1.2 http://kdahlquist.github.io/GRNmap/downloads.html)

**Comment by trixr4kdz** [comment]
I made another wiki page called "How to format the input file for GRNmap (beta)" to differentiate how to format the beta branch sheets from the master branch since everyone seems to be having errors from using the new formatting style even though the master branch has not caught up (so the latest release has also not caught up). When you use the latest release, be sure to use the formatting in the page **"How to format the input file for GRNmap"** -- note the lack of the "(beta)".

**Comment by kdahlquist** [comment]
I am closing this because it was due to a input sheet format/code mismatch.
