### ISSUE TITLE
MATLAB 2014b license expired in the Math Dept computers

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#157]
The license for the computers in the math department have apparently expired so we couldn't run the code there anymore.

**Comment by kdahlquist** [comment]
They have to be reactivated; it should be fairly straightforward, but it will take a faculty member to do it.  I will check the computers in my research lab right now (I will be able to reactivate) and submit a ticket for S120.

**Comment by kdahlquist** [comment]
I have manually activated the license on six computers in S120.  The three that are closest to the door in the first and second rows should work.  However, if they get restarted, the license file will be deleted.  

IT needs to update the license key server which will permanently fix this issue.  I'll let you know when it is fixed.

**Comment by kdahlquist** [comment]
IT reports that the license server has been updated and that one of the S120 computers has been manually checked.  I'll check this afternoon on a computer that we didn't modify yesterday, just to be sure, but I think this issue has been resolved.

The next time @juansc or @trixr4kdz are in the math department, they should try a computer there.  If it is still an issue, then reopen this because I'm going to close it now.
