### ISSUE TITLE
Error in calculation of MSE for optimization_diagnostics sheet

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#165]
This error was previously mentioned as part of issue #154; I am breaking this out separately so it can be dealt with on its own with its own thread.  I've copied the relevant comment from @trixr4kdz below:

"However, we spotted another discrepancy in the MSE calculations.

![0385a2dc-8e00-11e5-9951-f0b317e9e481](https://cloud.githubusercontent.com/assets/6463867/12286722/a5b5e214-b97b-11e5-83fa-fefa255856ba.PNG)

It would seem that the dcin5 MSE is the cumulative sum of both wt and dcin5 MSEs."

Once we have completed the branch clean up #164 and have finished making and testing the changes to the input sheet format, merging them into master, we can tackle reproducing this bug and then fixing it.

**Comment by bengfitzpatrick** [comment]
I have emailed Dr. Dahlquist the corrected file.  The code mod is as follows:
%     SSE(:,qq) = errormat/nSE;
    SSE(:,qq) = errMatStrain/nSE;
the errormat array is accumulating the errors over all strains being used, so that's where the cumulative computation crept in.

The current beta does not run for me.  I tried two test input files from the folders estimation tests and perturbation_tests\math_post_L-curve_corrected; neither would run.  The error given by MATLAB is:

Undefined function or variable 'L_curve'.

Error in readInputSheet (line 109)
GRNstruct.controlParams.L_curve                      = L_curve;

Error in GRNmodel (line 30)
GRNstruct = readInputSheet(GRNstruct);

**Comment by kdahlquist** [comment]
I sent @bengfitzpatrick an input file that runs with the current code.  I will also test it myself.  @juansc and @trixr4kdz are still in the process of fixing the test files so that they run with the current code as per issues #129 and #155.

**Comment by kdahlquist** [comment]
@kdahlquist has verified that this bug is fixed with one input file.  I have pushed @bengfitzpatrick's changes to the repository on the beta branch.

I will send @juansc and @trixr4kdz the input and output files used to verify the bug fix.

@bengfitzpatrick notes that in the output file, he did some calculations in Excel to verify that the correct computation was being made as follows:

MSE = SSE/(number of terms in the SSE sum).

Number of terms for individual MSE computations = number of slides = number slides at 15+number at 30+number at 60.
Number of terms in full LSE = (number slides)*(number genes) = (number of slides wt + number dcin5 + ...)*(number genes)

You can see  (a) that things are no longer cumulative by inspection and (b) the LSE matches the reconstructed MSE from the individual MSEs.

@juansc and @trixr4kdz, would you please write an unit test for this.

**Comment by juansc** [comment]
We created a unit test for this behavior.

**Comment by trixr4kdz** [comment]
Right now, the L-curve runs for 15 minutes for just the newly created test.

**Comment by kdahlquist** [comment]
For the future, we might investigate writing a test that takes a shorter time to run, but for now we do have a test that we can use, so we'll worry about that later.
