### ISSUE TITLE
Schedule unit testing work session

### ISSUE THREAD

**Issue by dondi** [kdahlquist/GRNmap#189]
@dondi needs to meet with the coding team to help guide the transition to more robust unit tests. Let's schedule via this issue.

**Comment by juansc** [comment]
Hello. I will not be at Cabo next week, so I will be available Monday, Tuesday, and Friday all day.

**Comment by dondi** [comment]
Tuesday looks good. What time(s) will be good for you? Late morning/early afternoon ok?

**Comment by juansc** [comment]
Early afternoon works for me. So 1pm or 2pm. @trixr4kdz, @cazinge what about you guys?

**Comment by kdahlquist** [comment]
I (@kdahlquist) could be available at that time.  Where are you guys going to meet?  You could use my research lab--S120 may not be available since Peter Alison is planning on running updates/installing software on those computers sometime this week.  If you really want to meet in there, I could check with him, let me know.

**Comment by trixr4kdz** [comment]
I can meet at 2pm.

**Comment by cazinge** [comment]
I can meet at any time this week.

**Comment by dondi** [comment]
Looks like Tuesday at 2pm then? That will work for me. Venue is then the last detail—see @kdahlquist’s comment above.

**Comment by juansc** [comment]
I am currently in S120 and there's no one here. We could use the research lab instead.

**Comment by kdahlquist** [comment]
I'm in my office and my research lab is open.

**Comment by dondi** [comment]
OK will see you all in LSB 2nd floor before 2.

**Comment by dondi** [comment]
This happened, and we reached TDD Inception. :+1:
