### ISSUE TITLE
Replace log2FC in output.m with GRNstruct.microData

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#203]
`GRNstruct.microData` and `log2FC` are identical copies of each other. We use `log2FC` in the code to pass certain data to the MATLAB built-in functions such as ODE45 and FMINCON. We use `log2FC` in output.m when we could be using `GRNstruct.microData`. An easy refactor is to use GRNstruct.microData instead of `log2FC`. This will also make the test fixtures for the output functionality easier to manage, since we wouldn't need to assign to `log2FC`.

**Comment by kdahlquist** [comment]
log2FC was the original one; GRNstruct.microData was the result of refactoring.  However log2FC was never removed.

log2FC is a global variable, so we can't just replace it right now.  However, @juansc in Issue #150 provided links to methods for passing more information to fmincon and ode45.

Benefit is restructuring testing to make it easier to avoid using the globals because now in between runs have to clear the global variables.

**Comment by kdahlquist** [comment]
I think this is related to #242; should these issues be merged?

**Comment by cazinge** [comment]
Double-checked that log2FC has been replaced with GRNstruct.microData in output.m. Closing this issue.
