### ISSUE TITLE
Prepare for the SoCal Systems Biology Conference Jan 28, 2017

### ISSUE THREAD

**Issue by bklein7** [kdahlquist/GRNmap#293]
This winter, UCI will be hosting the 7th annual Southern California Systems Biology Conference ([SCSB home page](http://ccbs.uci.edu/scsb2016home)). As of Nov. 28th, information regarding the 2017 SCSB conference has yet to be announced. However, we can anticipate that the conference will be held on Saturday, January 28th, 2017.

It is likely that we will update the posters developed for Experimental Biology (S'16) for this conference. However, if time permits and the data is there, we may wish to work on new posters over winter break.

**Comment by kdahlquist** [comment]
Abstracts are due Friday, Jan 20.  Please send me drafts ASAP.  It would actually be good to post them on a wiki, either OWW or GitHub for group editing.

**Comment by kdahlquist** [comment]
Abstract guidelines are here: http://ccbs.uci.edu/scsbc2017registration

There's a limit of 250 words.

**Comment by kdahlquist** [comment]
I have reviewed the poster; it looks good overall.  Here is my feedback:
Major:
* I may be misunderstanding, but I thought that the syntactic checker went first and then the semantic checker was second.  I think this because don't you have to convert the data before running the semantic checker?  It seems to me that you would check the Excel, SIF, or GraphML file first and if they pass, then go on to the conversion and semantic checker.  Let me know if I'm understanding this right because your flow chart has semantic first, then syntactic (the other way around).

Minor:
* The title needs to be the same as the submitted abstract:  "New features improve GRNsight: a web application and service for visualizing models of small- to medium-scale gene regulatory networks"
    * You can change the title for the LMU Symposium, but we are stuck with this one for now.
* The authors and order need to be the same as the submitted abstract, which is: Anindita Varshneya, Mihir Samdarshi, Nicole A. Anguiano, Yeon-Soo Shin, John David N. Dionisio, and Kam D. Dahlquist
    * Again we can change for the symposium.  The submitted abstract is in the repo under documents > abstracts.
* In the future we will want to replace the Excel spreadsheet images with the one used in the PeerJ paper and use the other figures from the paper, but for now it's fine.
* There are some minor wording changes (grammar, phrasing) needed throughout, but it will be easier for me to do them. 

Overall, I'll make the minor changes myself since it would take the same amount of time to type them here as fix the PowerPoint.  Please get back to me on the answer to the flow chart question.

**Comment by kdahlquist** [comment]
Posters are being printed; I'll bring them all together tomorrow.

**Comment by kdahlquist** [comment]
Nika and Natalie are driving. See you tomorrow at 7am.

**Comment by kdahlquist** [comment]
We are here and the final versions of the posters have been uploaded to the repository.
