### ISSUE TITLE
Create tests for existing LSE function

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#313]
Before we tackle #310, we need test coverage for the LSE function.

**Comment by dondi** [comment]
Based on @cazinge's initial code inspection, it looks like an LSE test suite does not yet exist, so it will need to be put together.

**Comment by jtorre39** [comment]
These variables change within General Least Squares Error and are likely candidates for testing. 

SSE 
prorate - if fixP
penalty_out
lse_out
b - if not fix_b

**Comment by jtorre39** [comment]
These variables change within Lse.m

* initial_guesses 
* estimated_guesses 
* lse_0 
* lse_final - which is accounted for in General Least Squares Error and does not need to be tested independently

**Comment by trixr4kdz** [comment]
Writing the tests for the LSE function is proving to be a bit tricky since we are not 100% sure of the correctness of the outputs. This circles back to what we discussed on Wednesday's meeting of the stochasticity/non-determinism of the Matlab functions that we are using. We can, however, assert that the current output of the function does not change during our implementation of the nested data structure. As a result, our idea of trying to make tests for LSE goes back to how I originally tried to write tests 2 summers ago. which is to run GRNmap using the 16 different parameter combinations and using those to check if our changes to the code dramatically affected our outputs. 

@cazinge proposed that, since this is dependent on issue #323 which creates a roadblock for us, we should work in parallel to make the transition into the new data structure, i.e., create a temporary function that uses the nested structure. Admittedly, this does not conform to TDD but because we won't be changing LSE directly and will instead be putting making the transition in some temporary file, we can take advantage of our meeting time to begin implementation. We can address this issue more in-depth in the next meeting.

**Comment by trixr4kdz** [comment]
For future reference, [here](https://onlinecourses.science.psu.edu/stat414/node/277) is a (somewhat) helpful link to the LSE formula:

**Comment by trixr4kdz** [comment]
Also, while looking through the gLSE routine, we had a question for @bengfitzpatrick of why the variables x1 and d are used in [this line](https://github.com/kdahlquist/GRNmap/blob/master/matlab/general_least_squares_error.m#L82). The "x1" and "d" variables seem to be about the same.

**Comment by trixr4kdz** [comment]
Nvm, I'm an idiot, the x is the answer to the ode45 solver.

**Comment by jtorre39** [comment]
Dr. Fitzpatrick gave us a run through of what is happening in general_least_squares_error. 
![Easy General Least Squares Error Calculations](https://cloud.githubusercontent.com/assets/16827894/23230248/1a1d5102-f8f8-11e6-818e-1371494b9d34.jpg)

**Comment by kdahlquist** [comment]
@cazinge and @jtorre39 got a top-down briefing (nano-symposium) on the LSE function from @bengfitzpatrick and the group confirmed that it is within reach to create a data set against which to test the correctness of the function. @trixr4kdz should get the same background sometime, and the group can potentially meet with @bengfitzpatrick again on Friday.

Based on this knowledge, the task of writing isolated LSE unit tests can proceed.

**Comment by kdahlquist** [comment]
I will also note that we are still going to do TDD and write the tests first and not try to implement the new data structure in parallel as suggested by @cazinge.  Test files with "artificial-data" in the filename have test data that can be used (in the text fixture, not by running the actual input file).

**Comment by dondi** [comment]
@dondi and @bengfitzpatrick took a look at the work in progress for the LSE unit tests and gave them a thumbs up. One to-do item is to round the test values in theta; the rest can stay the same.

The general approach for unit tests is to decouple them as much as possible from ancillary functionality such as I/O and parsing. Thus, filling out the data structure manually, even if data are just copied from the spreadsheet, is the proper setup for these tests.

**Comment by dondi** [comment]
To close this issue, we need to achieve sufficient code coverage. @cazinge and @trixr4kdz reported that a code coverage tool came in at 60%; they need to verify that the measurement is isolated to just coverage of gLSE correctness. If so, we can use this as one measure of sufficient coverage.

The second possibility is to list the known remaining cases. Ideally the code coverage tool and our sense of which cases are covered are congruent:

- [ ] Fix the theta values (round them)
- [ ] Increment a single data cell by 1; this should increase the answer by 1/nData
- [ ] Increment a single data cell by 2; this should increase the answer by 4/nData
- [ ] Increment _two_ data cells by 1 each; this should increase the answer by 2/nData
- [ ] Add asserts for the `strain_x1` output of the function (either use the output sheet for the correct answers or @bengfitzpatrick may be able to manually compute some cases); for cases where the test fixture itself came from the model, the output should be the same as the input
- [ ] Case(s) where there are two strains
- [ ] Test the penalty part of the calculation (i.e., `alpha != 0`): calculate `penalty_out` manually then try with `alpha == 1; alpha == 2`

**Comment by jtorre39** [comment]
The biggest relative error that we're getting is 9x10^-8 for incrementing a cell data for items in the above checklist 2-4 so we decided to compare the relative error with 1x10^-7 because at this point it is only due to precision errors as we are not sure how much to round.

**Comment by trixr4kdz** [comment]
I ran our code coverage for just gLSE and it turns out that the coverage is around 75%.
![codecoverageforglse](https://cloud.githubusercontent.com/assets/8975300/23569769/f2a0ad16-0015-11e7-9b13-4828ec54ffef.PNG)

**Comment by trixr4kdz** [comment]
If we run all of our test suites, the overall code coverage is below:
![allcodecoverage_part1](https://cloud.githubusercontent.com/assets/8975300/23570257/42ac8152-0018-11e7-9c0d-36742c7a0f9e.PNG)
![allcodecoverage_part2](https://cloud.githubusercontent.com/assets/8975300/23570259/44d1cafa-0018-11e7-85e3-9706e3ae59ea.PNG)

**Comment by jtorre39** [comment]
Added four test cases in a pull request which @trixr4kdz will look at. They are increment a single data cell by 2, increment two data cells by 1 each, trying with alpha == 1 and alpha ==2 which manual penalty_out calculations.

**Comment by trixr4kdz** [comment]
I am unable to assert the strain_x1 part of the output of gLSE since this output is not the same as the input like we thought from our previous meeting.

For instance, when I tried to test the 3-gene, 3-edge case, strain_x1 came up as a 3x3 matrix of all 1s. The strain_x1 for the 4-gene, 6-edge control case came up as having a 4x4 matrix of varying values.

**Comment by trixr4kdz** [comment]
I've added tests where there are 2 strains as input instead of only 1 strain. Something that I've noticed when I was checking for relative error of L is that the relative error decreased to around 1e-10 (we keep getting 1e-08 error with only 1 strain) when we I added the second strain.

**Comment by kdahlquist** [comment]
Assuming this is closable.
