### ISSUE TITLE
Compute Gephi stats "by hand" to verify we know how they are computed

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#344]
- [ ] we need to compute one example of each statistic by hand and compare to the Gephi results to verify that we know how Gephi is doing the computations
    - [ ] unweighted
        - [x] betweenness centrality
        - [x] closeness centrality
        - [ ] eigen centrality
        - [ ] eccentricity (@maggie-oneil notes that this one may be difficult)
    - [ ] weighted
        - [x] betweenness centrality
        - [x] closeness centrality
        - [ ] eigen centrality
        - [ ] eccentricity  (@maggie-oneil notes that this one may be difficult)

**Comment by kdahlquist** [comment]
@maggie-oneil can you comment here on the results of the closeness centrality computation?

**Comment by maggie-oneil** [comment]
The notes for closeness centrality can be found here http://www.openwetware.org/images/8/8f/MO_ClosesnessCentrality.pdf

**Comment by maggie-oneil** [comment]
Also it should be noted that it appears as though the calculation needs node x =/= y in order for the edge to be included. AKA self-regulation is not counted in the statistic for closeness centrality

**Comment by kdahlquist** [comment]
@maggie-oneil is working on weighted betweenness centrality right now.

**Comment by kdahlquist** [comment]
If this all doesn't get finished, we can pick it up next semester.

**Comment by kdahlquist** [comment]
@maggie-oneil will go through Gephi support, either the forum, facebook group or GitHub issue to find out the algorithm for eccentricity.

**Comment by maggie-oneil** [comment]
Closeness centrality computed by hand last semester showed Gephi was calculating this statistic as unweighted. 
Betweeness centrality and eigencentrality are in the process of being calculated right now, will work on this as well tomorrow. 
Eccentricity is calculated using an algorithm, so will contact Gephi to figure out how this statistic is being calculated specifically. will reach out using Github, then move on to the forum they have, and facebook.

**Comment by maggie-oneil** [comment]
Successfully contact Gephi for information on eccentricity algorithm, response from Gephi can be found at the following link : https://github.com/gephi/gephi/issues/1778

From now on, will use a fully connected 6 node network in order to calculate statistics generated by Gephi. This will ensure all statistics are equivalent for all nodes, and in doing this we can assume that statistics for larger networks can also be computed.

**Comment by maggie-oneil** [comment]
Generated a 6 node, 30 edge network as described in lab meeting yesterday. However, this graph, when run through Gephi, yielded a betweeness centrality of 0 for all nodes, because the shortest path between two nodes was the edge directly connecting them. To take care of this, I removed the edge going from B -> A, and then was able to calculate the betweeness centrality for node C in the graph. 

The calculations completed can be found at the following address:
http://www.openwetware.org/images/1/1f/9.14.17BetweenessCentralityCalcs_6node-29edge_MO.pdf

**Comment by maggie-oneil** [comment]
Gephi presentation for lab meeting can be found here:
https://docs.google.com/presentation/d/1qZcRpLLQH_p-EIdJ-VcgYF_JOxiuMmwwqY2EBgJL538/edit?usp=sharing

**Comment by kdahlquist** [comment]
At today's meeting, @kdahlquist suggested that @maggie-oneil take a close look at the Gephi stats for db5 to try to make sense of what the stats are telling us about the network.  Rank the stats (which should rank the genes by "importance", roughly) and explain why that gene is important in the network.  Or maybe we don't think that it is and we disagree with what the stats are saying.  In any event, we need to start interpreting the data biologically, instead of compiling more data.

**Comment by maggie-oneil** [comment]
Updated powerpoint for this week can be found here. 
[MO.10.4.17GraphUpdatesLabMeeting.pptx](https://github.com/kdahlquist/GRNmap/files/1357200/MO.10.4.17GraphUpdatesLabMeeting.pptx)
