### ISSUE TITLE
Removing log_2_expressions sheet

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#39]
When I looked at the [wiki](https://github.com/kdahlquist/GRNmap/wiki/How-to-interpret-the-output-file-for-GRNmap) I noticed that the log_2_expressions sheet was supposed to correspond to the log2expressions in the input sheet. The current implementation of the code creates the output sheet by making a copy of the input sheet and appending new sheets with data generated by the program. Does this mean that we can get rid of the log2_expressions sheet?

**Comment by kdahlquist** [comment]
I just wanted to let you know that I'm pretty swamped for the next couple of days and I won't be able to review/respond to your comments until our mini "Spring Break".  After our meetings a couple of weeks ago to discuss the input and output sheets, I had been intending to write up as issues the final version of what we want.  So, could you hold off on making any further changes to the input/output sheets until I've had a chance to write that stuff up?

Right now, what would be helpful is to figure out how to output the least squares error and penalty term values into an output sheet called "diagnostics" so that when @Nwilli31 and @GraceJohnson run the model, they can easily find this information.

**Comment by kdahlquist** [comment]
I'm closing this because I think it is supplanted by other issues.  I think the code is correctly preserving the input expression data and outputs the optimized expression data, so we don't need this.
