### ISSUE TITLE
@bklein7 work with @eileenchoe on color-blind-friendly node coloring scheme

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#396]
@eileenchoe is looking at options in D3 for node coloring schemes.  @bklein7 would you please review and get back to her on which are the easiest for you to distinguish.  Please see this link:

https://github.com/d3/d3-scale-chromatic#diverging

**Comment by bklein7** [comment]
@eileenchoe: Thank you for looking into implementing a color-blind friendly node coloring scheme. In general, the diverging spectra involving two color gradients rather than three are easier to distinguish. Among those with two color gradients, the most distinct to me are the "BrBG", "PuOR", and "RdGy" color schemes. In contrast, the center of the "PRGn" and "PiYG" spectra are somewhat indistinct. Regarding the diverging spectra with three or more color gradients, I greatly prefer the "RdYlBu" scheme, which I can relatively easily distinguish, to the other two options, which are far more indistinct.

Let me know if there is anything else that I can do to aid in this effort.

**Comment by eileenchoe** [comment]
@bklein7 thanks for the feedback! We will be proceeding with the 2-color gradient options, so I will start with implementing node coloring with the options you chose and will follow up with you again when I have concrete examples of what the node coloring will look like with those colors.

**Comment by kdahlquist** [comment]
This has been implemented on @eileenchoe's branch on GRNsight.
