### ISSUE TITLE
Preallocate GRNstruct Arrays to Zeros Arrays

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#51]
This will increase speed and possibly addresses issue #50.

We will include a clear all at the very beginning, but we may need to revisit this issue if we wish to run the model several times.

**Comment by kdahlquist** [comment]
Behavior that we want is:

We want to have matrices initialized to zero and of the correct size.

If you make two runs, you should be able to do that without clearing all the space.  You might want to save data from one run to compare it to data from the second run.

**Comment by kdahlquist** [comment]
Tasks:
* look through all the code and find all of the arrays that are used
* back up from there and pre-allocate them
* number of strains and then these things for each strain: number of timepoints and number of flasks (replicates) 
* number of sim times 
* number of genes
each xlsread should be of the format

[numDummyVar,characterDummyVar] = xlsread(File,Sheet)

all arrays can be sized and initialized before use, using the data in the numDummyVar array.

**Comment by kdahlquist** [comment]
Being worked on as part of #62

**Comment by kdahlquist** [comment]
@juansc says in issue #175 :

When we perform an L_curve we generate several output files. If we perform an L_curve and any of these output files are in the same directory at the time that we run it(because we did an L_curve before and are doing it again) we will have an error. A suggestion is to remove these output sheets before making another run.

But what this really is about is data persisting from run to run and not the output files.

**Comment by kdahlquist** [comment]
The coding team will review this at their next meeting on Tuesday.  @bengfitzpatrick is available to help with this because it is a pretty complicated data structure.

**Comment by kdahlquist** [comment]
Discussion of this issue has now been moved over to #231.
