### ISSUE TITLE
Put in News items related to starting Google Analytics

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#71]
Let's put in a retroactive News item that says:

We added Google Analytics tracking to count web page views.

**Comment by trixr4kdz** [comment]
Finished

**Comment by kdahlquist** [comment]
Can we make this mirror how it looks on the GRNsight News page (see September 18, 2014):

Page View Counter Implemented (headline)

We added Google Analytics tracking to count web page views. (body text)

**Comment by trixr4kdz** [comment]
Updated News page

**Comment by kdahlquist** [comment]
The sentence needs a period at the end.  Also, don't forget to change the last modified date on the web pages, it must be done manually.

**Comment by trixr4kdz** [comment]
Updated to include implementation of download counter + changed date last modified

**Comment by kdahlquist** [comment]
I don't actually see the line at the bottom of the web pages that shows the number of page views.  There should be a line on every page that says "This page has been accessed x times." substituting x for the page views.  See the GRNsight web site for placement.

Also, are you able to add the download counter to the Downloads page now?  The bottom of that page should read, ""This page has been accessed x times.  The GRNmap executable has been downloaded y times, and the GRNmap source code has been downloaded z times from this page."  y should be the sum total of all executable downloads (all versions) and z should be the sum total of downloads of the source code (all versions).

Could you change the text of the June 2 News item to read:

We added Google Analytics tracking to count the number of downloads of the GRNmap executable and source code from the Downloads page.  

Link the word "Downloads" to the downloads page.

**Comment by trixr4kdz** [comment]
I've implemented the pageview counter to the botton of each page of the GRNmap website and updated the News item about tracking downloads. Still need to implement download counter to the site though (i.e it's being tracked in GA, I just need to modify the page to show how many downloads we have so far)

**Comment by dondi** [comment]
Yes, sounds good. For downloads, you just have a separate call, with path=downloads (or was it just download? Use whatever you've been pushing for page views), then insert the result in a different element. The upload report at the bottom of the GRNsight home page (http://dondi.github.io/GRNsight/) gives you an example of how that would be done.

**Comment by trixr4kdz** [comment]
Ok but how will I go about it with the different versions we are tracking? Currently, we are tracking each version with "download/ [version#] _ [executable or source] "

**Comment by dondi** [comment]
If Google Analytics supports an aggregate query (e.g., all paths starting with downloads) then it is a matter of learning how to invoke that. If they cannot do aggregates then it may be necessary to write a loop that sums up the numbers for each known version.

I need to look at the query interface first then we can decide what to do based on that.

**Comment by trixr4kdz** [comment]
@dondi I was trying to just make the download counter show up for each of the versions with this snippet
```
if (location.pathname.split("/").pop() === "downloads.html") {
    var version = $('div.panel panel-default').find('id').attr('id');
    $.getJSON("http://grnsight.cs.lmu.edu/beta/server/grnmap?path=download" + "/" + version, function (downloadCount) {
        $(".ga-download").text(downloadCount);
    })
}
```
But it didn't work :( I'm not very familiar with jquery so I'm not quite sure what's wrong. To explain what I was trying to do, since the [version#]_[executable or source] part of the virtual URL that tracks button clicks is the same as the id for that particular downloadable (e.g. version 1.0.10 executable is tracked with GRNmap/download/v1_0_10_executable and id="v1_0_10_executable"), I thought I could just append that to the end so I could retrieve the data for each individual version.

**Comment by dondi** [comment]
OK, first things first, I don't actually see any elements on the downloads page that match `$(".ga-execDownload")` nor `$(".ga-sourceDownload")`. That by itself will keep you from seeing anything.

Make sure you have elements like these on your page. These are the placeholders that will subsequently receive the numbers:

    <span class="ga-execDownload"></span>
    <span class="ga-sourceDownload"></span>

Once you see the numbers come in, I have a subsequent, deeper question: Do you want to display the download numbers for each version separately, or do you want to add all of them up and report the total? The answer to that may change your JavaScript code somewhat.

But try those additional elements first, then get back to me on the second question.

**Comment by trixr4kdz** [comment]
Oh right I was working on a practice branch that I deleted right away, but I've made the changes so gh-pages should have those classes now. The numbers still aren't popping up even with these though.

To make it clear in the meantime, I believe we want to sum up the executable downloads separately from the source code downloads. In GA, we have them both under "GRNmap/download" and I haven't figured out how to separate the overall downloads into the two since they only differ by what they end with: "_executable" or "_source". I had this weird idea that we would be summing them anyway so maybe we can take the hits individually and then sum them after

**Comment by dondi** [comment]
OK, it will take additional code to get things just right, but for now, just to get numbers in, change these lines in *ga-report.js*:

        var exec = $(this.attr('class')).closest('div[id$="_executable"]').attr('id');
        var source = $(this.attr('class')).closest('div[id$="_source"]').attr('id');

Change them to:

        var exec = $('div[id$="_executable"]').attr('id');
        var source = $('div[id$="_source"]').attr('id');

Those should get numbers in the elements. They won’t all be the right numbers yet, but once you get to that point we can then refine things.

Now that I see where the elements are, I see what you intended to do initially. But we should finalize an approach (individual vs. sum vs. others) because that determines the way we will code this up (beyond the quick fix above).

**Comment by trixr4kdz** [comment]
Alright, I've changed the two lines

**Comment by dondi** [comment]
OK sounds good, now the numbers do show up. Doing it per-version is a little more involved, so I will do that then you can see how it was done when I am finished. Mainly instead of a single `getJSON` call you need to iterate through all the version numbers and make one invocation per item. Then you also sum things up gradually in order to get the overall totals at the end. I'll signal when this is in (probably on the other ticket because that is specifically about downloads). You can probably close this one for the general analytics work.

**Comment by trixr4kdz** [comment]
@dondi fixed the download counter to sum up the totals for both source code and executables. He also separated the downloads for each version which you can see if you open up one of the sections. The News item from a previous comment has been updated to reflect the changes

**Comment by kdahlquist** [comment]
confirmed and closing
