### ISSUE TITLE
Compute within-strain ANOVA p-values and write to output workbook

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#73]
* Create a module in GRNmap to calculate 2-strain ANOVA p-value

**Comment by kdahlquist** [comment]
I modified the name of this issue.  We want to be as specific as possible when naming an issue and try to keep it so that one issue = one task.

What I was talking about in the meeting was actually the within-strain ANOVA.  I guess it could be possible to also do the between-strain ANOVA, but I think we would need to discuss that more.

The reason why I was suggesting to do this was to facilitate later visualization of the expression data by GRNsight using p value as a criterion for coloring (like we do in GenMAPP).

Another way to handle that would be to have the user provide that data, though, so this is a low priority for right now.

**Comment by kdahlquist** [comment]
@bengfitzpatrick is going to look at the within-strain ANOVA code to check for accuracy and with a view towards implementing this.

**Comment by kdahlquist** [comment]
I'm going to close this and tag it with the label "backlog" because it is not a priority right now.
